Dashboard design done
danialsyed6/student-portal pull request #3
Opened 2022-09-13 13:58 UTC by danialsyed6

2022-09-14 05:53 UTC, IshfaqAhmedAwan requested changes

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/components/dashboard/dropdown/index.tsx
> +            <span>Add</span>
Use select from material ui instead of this

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/components/dashboard/flag/index.tsx
> +      <p className="flag_title">{title}</p>
name this component meaningfully like gradeFlag or gradeBox etc

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/components/dashboard/miniFlag/index.tsx
> +    <div className="miniflag red">
Change the name so it should be understood why it is using for like tableGradeFlag as we will be using it in table to show grade

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/utils/getDate.ts
> +  if (hours === 0) return `${hoursP12}.${minutes} AM`;
We can use moment to format date and time

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/utils/getDate.ts
> +  const date = `${month} ${day}, ${year}`;
We can use moment to format date and time.
https://medium.com/how-to-react/format-your-date-or-time-in-react-js-using-moment-js-89c5c6e4f174

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/utils/index.ts
> +export { default as getDate } from './getDate';
Why we need extra file to export getDate?

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/components/dashboard/table/index.tsx
> +          <th className="th">Action</th>
Use material ui table

2022-09-14 05:53 UTC, IshfaqAhmedAwan commented on src/components/dashboard/button/index.tsx
> +      onClick={onClick}
Use material ui button instead of this component

2022-09-14 06:00 UTC, danialsyed6 commented on src/utils/index.ts
> +export { default as getDate } from './getDate';
If there are more utils then they can be imported in one line.

2022-09-14 06:36 UTC, JavedAhmadDeveloper commented on src/utils/getDate.ts
> +  if (hours === 0) return `${hoursP12}.${minutes} AM`;
create a file helper.ts and which will hold all helper functions

2022-09-14 06:41 UTC, JavedAhmadDeveloper commented on src/utils/index.ts
> +export { default as getDate } from './getDate';
we don't need to import and export again. we can directly export drop helper file of relevant

2022-09-14 06:48 UTC, JavedAhmadDeveloper commented on src/components/dashboard/dropdown/index.tsx
> +  // const dropdownRef = useRef<LegacyRef<HTMLDivElement>>();
rename it because it has actions inside it its not drop down

2022-09-14 06:49 UTC, JavedAhmadDeveloper commented on src/components/dashboard/dropdown/index.tsx
> +        </ul>
receive these as props because if we need later action menu we can use it just by changing props

2022-09-14 06:50 UTC, JavedAhmadDeveloper commented on src/components/dashboard/dropdown/index.tsx
> +          </li>
use Mui instead of css

2022-09-14 06:51 UTC, JavedAhmadDeveloper commented on src/components/dashboard/flag/index.tsx
> +      <p className="flag_title">{title}</p>
use MUi all over

2022-09-14 06:52 UTC, JavedAhmadDeveloper commented on src/components/dashboard/index.tsx
> +
your components should not contain data move this inside helper or inside utils with data.ts

2022-09-14 12:25 UTC, JavedAhmadDeveloper commented on src/components/dashboard/gradeFlag/index.tsx
> +    </Paper>
use typography

2022-09-14 12:31 UTC, JavedAhmadDeveloper requested changes

2022-09-14 12:31 UTC, JavedAhmadDeveloper commented on src/components/dashboard/tableGradeFlag/style.ts
> +  miniflagRed: { backgroundColor: 'rgba(255, 104, 151, 0.5)' },
export all objects individually and use them where you needed

2022-09-15 06:27 UTC, JavedAhmadDeveloper requested changes

2022-09-15 06:27 UTC, JavedAhmadDeveloper commented on src/components/dashboard/index.tsx
> +
it still in the component .. make data.ts in in utils

2022-09-15 07:14 UTC, IshfaqAhmedAwan requested changes

2022-09-15 07:14 UTC, IshfaqAhmedAwan commented on src/components/dashboard/table/index.tsx
> +import { dateStyle, timeStyle } from './styles';
import them in this order : react imports at top, mui imports then other external libraries like moment and then local imports.
You should also keep lines in ascending order, that means small line at top.
For example:
This :_
import { IStudent } from '../../../state/ducks/student/types';
import TableGradeFlag from '../tableGradeFlag';
import OptionsMenu from '../optionsMenu';
should be like this :_
import OptionsMenu from '../optionsMenu';
import TableGradeFlag from '../tableGradeFlag';
import { IStudent } from '../../../state/ducks/student/types';

2022-09-15 08:19 UTC, ahmadfaraz629 approved these changes
LGTM 👍

2022-09-15 08:21 UTC, IshfaqAhmedAwan approved these changes

2022-09-15 08:21 UTC, merged