Student Form Design and Validation Complete
danialsyed6/student-portal pull request #4
Opened 2022-09-15 11:30 UTC by danialsyed6

Created UI for student add/edit form. Applied validation using react hook form.

2022-09-15 12:50 UTC, ahmadfaraz629 commented on src/components/studentForm/index.tsx
> +  };
Use proper types for data

2022-09-15 12:50 UTC, ahmadfaraz629 commented on src/components/dashboard/optionsMenu/index.tsx
>  const ITEM_HEIGHT = 48;
tacke this through css or move it to the 
utils/constant.js file

2022-09-15 12:50 UTC, ahmadfaraz629 commented on src/components/studentForm/index.tsx
> +  const formFor = useLocation().pathname.includes('add') ? 'Add' : 'Edit';
make enum for Add and Edit. 
FormType

2022-09-15 12:50 UTC, ahmadfaraz629 commented on src/components/dashboard/index.tsx
> +import { useNavigate } from 'react-router-dom';
Re arrange the imports.
Built in
components
styles
utils

2022-09-15 12:50 UTC, ahmadfaraz629 commented on src/components/common/inputSelect.tsx
> +  }, [errorObj, name, value]);
No need for this code.
You are introducing a state which will cause this component render twice.

you can use 
const isError = !!errorObj

2022-09-15 12:50 UTC, ahmadfaraz629 commented on src/components/studentForm/index.tsx
> +  const [error, setError] = useState(false);
Not sure why this state is used here. what kind of error you are expecting.

Read error from hookform directly

2022-09-15 12:54 UTC, danialsyed6 commented on src/components/studentForm/index.tsx
> +  const [error, setError] = useState(false);
Some MUI components require a boolean value for the error. That is why this is used.

2022-09-15 13:14 UTC, alitjanjua commented on src/components/studentForm/index.tsx
> +  const [error, setError] = useState(false);
you can make any error boolean using double exclamatory sign i.e.( !! )

2022-09-16 06:47 UTC, IshfaqAhmedAwan requested changes

2022-09-16 06:47 UTC, IshfaqAhmedAwan commented on src/components/studentForm/index.tsx
> +          sx={titleStyles}
I could not understand why are we setting this state "setError" on click of typography

2022-09-16 06:47 UTC, IshfaqAhmedAwan commented on src/components/studentForm/index.tsx
> +import { FORM_TYPE } from '../../state/utils/enums';
Again order of import is not followed as asked.

2022-09-16 06:58 UTC, danialsyed66 commented on src/components/studentForm/index.tsx
> +import { FORM_TYPE } from '../../state/utils/enums';
Ahmad bhai said to put components first.

2022-09-16 06:59 UTC, danialsyed66 commented on src/components/studentForm/index.tsx
> +          sx={titleStyles}
I did it during testing and forgot to remove it.

2022-09-16 07:03 UTC, IshfaqAhmedAwan commented on src/components/studentForm/index.tsx
> +import { FORM_TYPE } from '../../state/utils/enums';
ok

2022-09-16 07:18 UTC, ahmadfaraz629 commented on src/App.tsx
> +        <Route path="/editStudent/:id" element={<StudentFormContainer />} />
change the routes
/student
/student/:id

2022-09-16 07:18 UTC, ahmadfaraz629 commented on src/components/common/inputText.tsx
> +  name: 'name' | 'marks';
why are we using name and marks as a type ? instead of string

2022-09-16 07:20 UTC, danialsyed6 commented on src/components/common/inputText.tsx
> +  name: 'name' | 'marks';
the name was defined by Yup schema so it was only taking 4 values 'name' | 'marks' | 'grade' | 'subject'

2022-09-16 07:32 UTC, ahmadfaraz629 approved these changes
LGTM 👍

2022-09-16 07:36 UTC, IshfaqAhmedAwan approved these changes

2022-09-16 07:36 UTC, merged